name: Build and Push Docker image
on:
  push:
    branches:
      - main  # Change to the branch you want to trigger this workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      id: build_image
      run: >
        IMAGE_TAG=$(date +%s)
        docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/actions:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Push Docker image
      run: >
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/actions:${{ env.IMAGE_TAG }}

    - name: done
      run: echo "Your image is packed and deployed to dckr-hub"